#application: gdgnantes
#version: 1
#runtime: go
#api_version: go1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "30d"

handlers:
# css files
- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)
  
#c ss files in directory (sublevel1)
- url: /(.+)/(.*\.css)
  mime_type: text/css
  static_files: static/\1/\2
  upload: static/(.+)/(.*\.css)
  
# js files
- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)

# js files in directory (sublevel1)
- url: /(.+)/(.*\.js)
  mime_type: text/javascript
  static_files: static/\1/\2
  upload: static/(.+)/(.*\.js)

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: static/\1
  upload: static/(.*\.(bmp|gif|ico|jpeg|jpg|png))
  
# image files in directory (sublevel1)
- url: /(.+)/(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: static/\1/\2
  upload: static/(.+)/(.*\.(bmp|gif|ico|jpeg|jpg|png))
  
# compressed files
- url: /(.*\.(bz2|gz|rar|tar|tgz|zip))
  static_files: static/\1
  upload: static/(.*\.(bz2|gz|rar|tar|tgz|zip))
  
# PDF files
- url: /(.*\.(pdf))
  static_files: static/\1
  upload: static/(.*\.(pdf))
  
# PDF files in directory (sublevel1)
- url: /(.+)/(.*\.(pdf))
  static_files: static/\1/\2
  upload: static/(.+)/(.*\.(pdf))
 
# index files
- url: /(.+)/
  static_files: static/\1/index.html
  upload: static/(.+)/index.html
  expiration: "15m"
 
- url: /(.+)
  static_files: static/\1/index.html
  upload: static/(.+)/index.html
  expiration: "15m"
 
# site root
- url: /
  static_files: static/index.html
  upload: static/index.html
  expiration: "15m"